export const tasks = [
    {
      id: 1,
      title: "Clean the living room and kitchen",
      userId: 101,
      helperId: 201,
      category: "Cleaning",
      imageUrl: "https://example.com/image1.jpg",
      price: 50,
      description: "Clean the living room and kitchen",
      address: "123 Main St, Los Angeles, CA",
      completed: false,
      estimatedDuration: "2h",
      createdAt: "2025-09-01T10:00:00Z",
      updatedAt: "2025-09-01T10:00:00Z"
    },
    {
      id: 2,
      title: "Mow the lawn and trim bushes",
      userId: 102,
      helperId: 202,
      category: "Gardening",
      imageUrl: "https://example.com/image2.jpg",
      price: 70,
      description: "Mow the lawn and trim bushes",
      address: "456 Oak Ave, San Diego, CA",
      completed: true,
      estimatedDuration: "3h",
      createdAt: "2025-09-02T11:00:00Z",
      updatedAt: "2025-09-03T15:00:00Z"
    },
    {
      id: 3,
      title: "Help move furniture into truck",
      userId: 103,
      helperId: 203,
      category: "Moving",
      imageUrl: "https://example.com/image3.jpg",
      price: 120,
      description: "Help move furniture into truck",
      address: "789 Pine Rd, San Jose, CA",
      completed: false,
      estimatedDuration: "5h",
      createdAt: "2025-09-03T09:30:00Z",
      updatedAt: "2025-09-03T09:30:00Z"
    },
    {
      id: 4,
      title: "Math tutoring for high school algebra",
      userId: 104,
      helperId: 204,
      category: "Tutoring",
      imageUrl: "https://example.com/image4.jpg",
      price: 40,
      description: "Math tutoring for high school algebra",
      address: "321 Elm St, Sacramento, CA",
      completed: false,
      estimatedDuration: "1.5h",
      createdAt: "2025-09-04T12:00:00Z",
      updatedAt: "2025-09-04T12:00:00Z"
    },
    {
      id: 5,
      title: "Deliver groceries from store",
      userId: 105,
      helperId: 205,
      category: "Delivery",
      imageUrl: "https://example.com/image5.jpg",
      price: 25,
      description: "Deliver groceries from store",
      address: "654 Maple Dr, Fresno, CA",
      completed: true,
      estimatedDuration: "45m",
      createdAt: "2025-09-05T14:00:00Z",
      updatedAt: "2025-09-05T15:00:00Z"
    },
    {
      id: 6,
      title: "Walk the dog in the evening",
      userId: 106,
      helperId: 206,
      category: "Pet Care",
      imageUrl: "https://example.com/image6.jpg",
      price: 30,
      description: "Walk the dog in the evening",
      address: "987 Cedar Ln, Oakland, CA",
      completed: false,
      estimatedDuration: "1h",
      createdAt: "2025-09-05T18:00:00Z",
      updatedAt: "2025-09-05T18:00:00Z"
    },
    {
      id: 7,
      title: "Prepare dinner for 4 people",
      userId: 107,
      helperId: 207,
      category: "Cooking",
      imageUrl: "https://example.com/image7.jpg",
      price: 60,
      description: "Prepare dinner for 4 people",
      address: "135 Birch Blvd, San Francisco, CA",
      completed: false,
      estimatedDuration: "2.5h",
      createdAt: "2025-09-06T09:00:00Z",
      updatedAt: "2025-09-06T09:00:00Z"
    },
    {
      id: 8,
      title: "Fix Wi-Fi connectivity issue",
      userId: 108,
      helperId: 208,
      category: "IT Support",
      imageUrl: "https://example.com/image8.jpg",
      price: 80,
      description: "Fix Wi-Fi connectivity issue",
      address: "246 Willow Way, Palo Alto, CA",
      completed: true,
      estimatedDuration: "1h",
      createdAt: "2025-09-06T10:30:00Z",
      updatedAt: "2025-09-06T12:00:00Z"
    },
    {
      id: 9,
      title: "Watch kids for the evening",
      userId: 109,
      helperId: 209,
      category: "Babysitting",
      imageUrl: "https://example.com/image9.jpg",
      price: 100,
      description: "Watch kids for the evening",
      address: "357 Cypress Ct, Irvine, CA",
      completed: false,
      estimatedDuration: "6h",
      createdAt: "2025-09-06T13:00:00Z",
      updatedAt: "2025-09-06T13:00:00Z"
    },
    {
      id: 10,
      title: "Wash and vacuum car",
      userId: 110,
      helperId: 210,
      category: "Car Wash",
      imageUrl: "https://example.com/image10.jpg",
      price: 20,
      description: "Wash and vacuum car",
      address: "468 Redwood St, Pasadena, CA",
      completed: true,
      estimatedDuration: "1h",
      createdAt: "2025-09-06T15:00:00Z",
      updatedAt: "2025-09-06T16:00:00Z"
    }
  ];
  